global:
  scrape_interval: 15s

scrape_configs:
  # --- NestJS Microservices ---
  - job_name: 'nest-services'
    static_configs:
      - targets:
          - 'api-gateway:4000'
          - 'auth-service:3001'
          - 'contracts-service:3002'
          - 'templates-service:3003'
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):(\d+)'
        target_label: instance
        replacement: '$1'

  # --- Next.js Frontend (si expone métricas personalizadas) ---
  # - job_name: 'frontend'
  #   static_configs:
  #     - targets: ['web:3000']
  #   metrics_path: /metrics

  # --- Redis Exporter (opcional) ---
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:9121']

  # --- PostgreSQL Exporter (opcional) ---
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:9187']