apiVersion: 1

# Configura Prometheus como datasource por defecto
# Se monta en /etc/grafana/provisioning/datasources/
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
